<?php
// @codingStandardsIgnoreFile
/** @var \Ingenico\Payment\Block\Method\View $block */

use IngenicoClient\OrderField;
use IngenicoClient\PaymentMethod\PaymentMethod;

?>

<?php if ($html = $block->getSecurityHTMLAnswer()): ?>
    <?php // 3DSec HTML data ?>
    <?php echo /* @noEscape */ $html; ?>
<?php else: ?>
    <?php if ($data = $block->getOpenInvoicePaymentData()): ?>
        <?php
        // Mark order status "Redirected"
        $block->setOrderRedirected();
        ?>
        <div class="ingenico-confirmation">
            <div class="ingenico-loader">
                <img src="<?php echo $block->escapeHtmlAttr($block->getLoaderUrl()); ?>" alt="<?= __('checkout.please_wait'); ?>">
            </div>
            <form id="ingenico-hosted-checkout-form" method="post" action="<?= $block->escapeHtmlAttr($data['url']); ?>" accept-charset="utf-8" style="display:none">
                <?php foreach ($data['fields'] as $key => $value): ?>
                    <input type="hidden" name="<?php echo $block->escapeHtmlAttr($key); ?>" value="<?php echo $block->escapeHtmlAttr($value); ?>">
                <?php endforeach; ?>
            </form>
        </div>

        <script>
            // Submit form
            window.addEventListener("DOMContentLoaded", function () {
                document.getElementById("ingenico-hosted-checkout-form").submit();
            });
        </script>
    <?php else: ?>
    <div class="ingenico-confirmation">
        <ul>
            <?php foreach ($block->getPaymentMethods() as $categoryName => $methods): ?>
                <?php foreach ($methods as $code => $method): ?>
                    <?php /** @var \IngenicoClient\PaymentMethod\PaymentMethod $method */?>
                    <li>
                    <?php // AFTERPAY & KLARNA ?>
                    <?php if ($method->getAdditionalDataRequired()): ?>
                        <?php $missingFields = $method->getMissingFields(); ?>
                        <div class="payment-logo">
                            <img src="<?php echo $method->getEmbeddedLogo(); ?>" alt="<?php echo __($method->getName()) ?>" title="<?php echo __($method->getName()) ?>" width="50" />
                            <h3><?php echo $block->escapeHtmlAttr(__($method->getName())) ?></h3>
                        </div>
                        <div class="form-container">
                            <form
                                action="<?php echo $block->escapeHtmlAttr($block->getOpenInvoicePostUrl()) ?>"
                                method="post"
                                id="open-invoice"
                                data-hasrequired="<?php echo $block->escapeHtmlAttr(__('* Required Fields')) ?>"
                                data-mage-init='{"validation":{}}'>

                                <input type="hidden" name="payment_id" value="<?php echo $block->escapeHtmlAttr($method->getId()) ?>" />
                                <input type="hidden" name="pm" value="<?php echo $block->escapeHtmlAttr($method->getPM()) ?>" />
                                <input type="hidden" name="brand" value="<?php echo $block->escapeHtmlAttr($method->getBrand()) ?>" />

                                <?php if (count($missingFields) > 0): ?>
                                    <h4 class="subtitle"><?= __('modal.openinvoice.additional_data_required'); ?></h4>

                                    <fieldset class="fieldset">
                                        <?php
                                        foreach ($missingFields as $field):
                                            $name = $field->getFieldName();
                                            $type = $field->getFieldType();
                                            $required = $field->getRequired() ? ' required' : '';
                                            $value = $field->getValue();
                                            $length = $field->getLength();
                                            $id = implode('-', [$method->getId(), $type, $name, hash('sha256', $value)]);
                                            ?>
                                            <div class="field <?php echo $block->escapeHtmlAttr($name) ?><?php echo $block->escapeHtmlAttr($required); ?>">
                                                <label class="label" for="<?php echo $block->escapeHtmlAttr($id) ?>"><span><?php echo $block->escapeHtmlAttr($field->getLabel()); ?></span></label>
                                                <div class="control">
                                                    <?php if ($type === 'radio'): ?>
                                                        <?php foreach ($field->getValues() as $key => $value): ?>
                                                    <input
                                                        name="<?php echo $block->escapeHtmlAttr($name); ?>"
                                                        id="<?php echo $block->escapeHtmlAttr($id) ?>"
                                                        title="<?php echo $block->escapeHtmlAttr($value) ?>"
                                                        value="<?php echo $block->escapeHtmlAttr($key) ?>"
                                                        class="input-radio"
                                                        type="<?php echo $block->escapeHtmlAttr($type) ?>"
                                                        data-validate="{required:true}" >
                                                        <label class="label" for="<?php echo $block->escapeHtmlAttr($id) ?>">
                                                            <span><?php echo $block->escapeHtmlAttr($value) ?></span>
                                                        </label>
                                                    <br/>
                                                    <?php endforeach; ?>
                                                    <?php else: ?>
                                                    <input
                                                        name="<?php echo $block->escapeHtmlAttr($name); ?>"
                                                        id="<?php echo $block->escapeHtmlAttr($id); ?>"
                                                        title="<?php echo $block->escapeHtmlAttr($value) ?>"
                                                        value="<?php echo ($type === 'date' && is_numeric($field->getValue())) ? $block->escapeHtmlAttr(date('d-m-Y', $field->getValue())) : $block->escapeHtmlAttr($field->getValue()); ?>"
                                                        class="input-<?php echo $block->escapeHtmlAttr($type); ?><?php echo $length ? $block->escapeHtmlAttr(' validate-length maximum-length-'.$length) : '' ?>"
                                                        type="<?php echo $type === 'date' ? 'text' : $block->escapeHtmlAttr($type); ?>"
                                                        data-validate="{<?php echo $field->getRequired() ? 'required:true' : ''; ?>}" >

                                                    <?php if ($type === 'date'): ?>
                                                        <script>
                                                            require(["jquery", "mage/calendar"], function($){
                                                                $("#<?php echo $block->escapeHtmlAttr($id); ?>").datepicker({
                                                                    showMonthAfterYear: false,
                                                                    dateFormat:'dd-mm-yy',
                                                                    changeMonth: true,
                                                                    changeYear: true,
                                                                    yearRange: '<?php echo '1940:' . date('Y'); ?>',
                                                                    defaultDate: '-1y'
                                                                });
                                                            });
                                                        </script>
                                                    <?php endif; ?>
                                                    <?php endif; ?>
                                                </div>
                                            </div>
                                        <?php endforeach; ?>
                                    </fieldset>
                                    <div class="actions-toolbar">
                                        <div class="primary">
                                            <input type="hidden" name="hideit" id="hideit" value="" />
                                            <button type="submit" title="<?php echo $block->escapeHtmlAttr(__('Proceed')) ?>" class="action submit primary">
                                                <span><?= __('Proceed'); ?></span>
                                            </button>
                                        </div>
                                    </div>
                                <?php else: ?>
                                    <?php // Submit the form if there aren't any missing fields ?>
                                    <div class="ingenico-loader">
                                        <img src="<?php echo $block->escapeHtmlAttr($block->getLoaderUrl()); ?>" alt="<?= __('checkout.please_wait'); ?>">
                                    </div>
                                    <script>
                                        // Submit form
                                        window.addEventListener("DOMContentLoaded", function () {
                                            document.getElementById("open-invoice").submit();
                                        });
                                    </script>
                                <?php endif; ?>
                            </form>
                        </div>
                        <?php // REDIRECT PMs ?>
                    <?php elseif ($method->isRedirectOnly()): ?>
                        <a href="<?php echo $method->getIFrameUrl(); ?>">
                            <div class="payment-logo">
                                <img src="<?php echo $method->getEmbeddedLogo(); ?>" alt="<?php echo $block->escapeHtmlAttr($method->getName()) ?>" width="50" />
                                <h3><?php echo $block->escapeHtmlAttr($method->getName()); ?></h3>
                            </div>
                        </a>
                        <?php // IFRAME PMs ?>
                    <?php else: ?>
                        <?php if ($method->getSubmethodLogos()){ ?>
                            <div class="payment-logo">
                            <?php foreach ($method->getSubmethodLogos() as $name => $logoSrc){ ?>
                                <img src="<?php echo $logoSrc; ?>" alt="<?php echo $block->escapeHtmlAttr($name); ?>" title="<?php echo $block->escapeHtmlAttr($name); ?>" width="50" />
                            <?php } } else { ?>
                            <div class="payment-logo">
                            <img src="<?php echo $method->getEmbeddedLogo(); ?>" alt="<?php echo $block->escapeHtmlAttr($method->getName()) ?>" title="<?php echo $block->escapeHtmlAttr($method->getName()) ?>" width="50" />
                            <h3><?php echo $block->escapeHtmlAttr($method->getName()) ?></h3>
                        <?php } ?>
                        </div>
                        <iframe data-src="<?php echo $block->escapeHtmlAttr($method->getIFrameUrl()); ?>" title="Payment Form" lazyload="on"></iframe>
                    <?php endif; ?>
                <?php endforeach; ?>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
    <?php endif; ?>
<script>
    require(['Magento_Customer/js/customer-data'], function(customerData) {
        customerData.getInitCustomerData().then(function() {
            customerData.invalidate(['cart','cart-data']);
        });
    });
</script>
<?php endif; ?>
