<?php
// @codingStandardsIgnoreFile
/**
 * @var $block \Ingenico\Payment\Block\Form\Method
 */
$code = $block->escapeHtml($block->getMethodCode());
?>

<div id="payment_form_<?php echo $block->escapeHtml($code); ?>" class="<?php echo $block->escapeHtml($code); ?>">
    <fieldset class="fieldset payment items payment-method <?php echo $block->escapeHtml($code); ?>" id="payment_form_<?php echo $block->escapeHtml($code); ?>" style="display: none;">

    </fieldset>
</div>
